language: generic
sudo: false

cache:
    directories:
        - $HOME/.stack

matrix:
  fast_finish: true
  include:
    - env: GHCVER=8.0.1 STACK_YAML=stack.yaml
      compiler: ": #stack 8.2.1"
      addons: {apt: {packages: [ghc-8.2.1], sources: [hvr-ghc]}}


before_install:
 - unset CC
 - export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:$PATH
 - ./.travis-setup.sh

install:
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - stack --no-terminal test --only-dependencies


script:
 - set -e; stack --no-terminal test --haddock --no-haddock-deps --ghc-options="-Werror"