#!/bin/bash

mkdir -p /etc/bash_completion.d
mv /usr/hapidry /etc/bash_completion.d/
hapidry-generate

ZSH=/etc/zsh/zshrc

if [ -f $ZSH ]
then
    last=$(tail -n 1 $ZSH)
    if [[ $last == "source /etc/bash_completion.d/hapidry" ]]; then
        :
    else
        echo 'autoload bashcompinit' >> $ZSH
        echo 'bashcompinit' >> $ZSH
        echo 'source /etc/bash_completion.d/hapidry' >> $ZSH
    fi
fi